version: '3.8'

services:
  # Telegram Bot Service (standalone)
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-stock-bot-telegram-standalone
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BACKEND_API_URL=${BACKEND_API_URL:-http://localhost:3000/api}
      - BACKEND_API_TIMEOUT=${BACKEND_API_TIMEOUT}
      - DEMO_MODE=${DEMO_MODE}
    networks:
      - ai-stock-bot-network
    profiles:
      - bot

# Custom network for service communication
networks:
  ai-stock-bot-network:
    driver: bridge
    name: ai-stock-bot-network
