version: '3'

services:
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-image-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Uncomment to run in demo mode
      # - DEMO_MODE=true
    volumes:
      - ./temp:/app/temp
